#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# Arch Linux Repo DB to Sqlite DB
#

import tempfile
import tarfile
import os
import re
import gzip
import shutil

# Creating temporary folders
work_dir = tempfile.mkdtemp()

# Official repository
repo_list = ['core', 'extra']
for repo in repo_list:
    # Decompress {repo}.files
    repo_path = f'{work_dir}/{repo}'
    with tarfile.open(f'/var/lib/pacman/sync/{repo}.files', 'r:gz') as tar:
        tar.extractall(repo_path)

    # Traverse the packages in the repository
    for pkg_in_repo in os.listdir(repo_path):
        pkg_full_path = os.path.join(repo_path, pkg_in_repo)
        if os.path.isdir(pkg_full_path):
            # Get accurate package name through desc file
            read_desc = open(f'{pkg_full_path}/desc', mode='r', encoding='utf-8').read()
            pkg_name = re.search('%NAME%\n(.+)', read_desc).group(1)
            # Get a list of files through files file.
            read_files = open(f'{pkg_full_path}/files', mode='r', encoding='utf-8').readlines()[1:]
            file_path = [f'/{file.strip()}' for file in read_files if not file.strip().endswith('/')]
            # Write data
            with gzip.open('arch-repo.db.gz', 'at', compresslevel=9) as gz:
                gz.write(f'{repo}/{pkg_name}: {file_path}\n')

# Clean up
shutil.rmtree(work_dir)
