#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# pacman -F
#

import sys
import sqlite3

if len(sys.argv) < 3:
    print("Usage: pacman-F '/path/to/arch-repo.db' '/path/to/your/file'")
    sys.exit(1)
arch_repo = sys.argv[1]
search_path = sys.argv[2]

conn_repo = sqlite3.connect(arch_repo)
crc = conn_repo.cursor()
query = '''
SELECT pkg_name FROM cmc_core WHERE file_path = ?
UNION
SELECT pkg_name FROM cmc_extra WHERE file_path = ?
'''
result = crc.execute(query, (search_path,search_path)).fetchall()

if result:
    print(result[0][0])
else:
    pass

conn_repo.close()
